// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYyLdEoFPgbcFpR4frmHxvGE_R_1HM1XM',
    appId: '1:908891812771:web:c0479242caeaabe656e016',
    messagingSenderId: '908891812771',
    projectId: 'nutriai-lexis',
    authDomain: 'nutriai-lexis.firebaseapp.com',
    storageBucket: 'nutriai-lexis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC9TMGfzJSubWDi4X0H5kmq1FNV0YaZzE',
    appId: '1:908891812771:android:c985fe23d4ee58f156e016',
    messagingSenderId: '908891812771',
    projectId: 'nutriai-lexis',
    storageBucket: 'nutriai-lexis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXLznw0_LYbsA7DbVvwyHothALhlk1vmE',
    appId: '1:908891812771:ios:bfc95dd3b075c69b56e016',
    messagingSenderId: '908891812771',
    projectId: 'nutriai-lexis',
    storageBucket: 'nutriai-lexis.firebasestorage.app',
    iosBundleId: 'com.example.frontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXLznw0_LYbsA7DbVvwyHothALhlk1vmE',
    appId: '1:908891812771:ios:bfc95dd3b075c69b56e016',
    messagingSenderId: '908891812771',
    projectId: 'nutriai-lexis',
    storageBucket: 'nutriai-lexis.firebasestorage.app',
    iosBundleId: 'com.example.frontEnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYyLdEoFPgbcFpR4frmHxvGE_R_1HM1XM',
    appId: '1:908891812771:web:52b46e73a64e9a8a56e016',
    messagingSenderId: '908891812771',
    projectId: 'nutriai-lexis',
    authDomain: 'nutriai-lexis.firebaseapp.com',
    storageBucket: 'nutriai-lexis.firebasestorage.app',
  );
}
